# Extraction of Regesta data from PDF files as tables.

## FUNCTIONS
Prepares the visualisation of the position of content and text.
The page content is extracted as dictionary/JSON (see <https://pymupdf.readthedocs.io/en/latest/app1.html#dict-or-json>)

### Import modules, define classes

In [25]:
import fitz  # PyMuPDF
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [26]:
class PDFProcessor:
    def __init__(self, parameter):
        self.doc = fitz.open(parameter['path'])
        # compute difference between PDF and printed page numbers
        self.page_diff = parameter['pdf_pages'][0] - parameter['first_print_page']
        self.pdf_page_range = range(parameter['pdf_pages'][0] - 1, min(parameter['pdf_pages'][1], len(self.doc)))

    def load_pages(self):
        pages = {}
        for pdf_page in self.pdf_page_range:
            page = self.doc.load_page(pdf_page)
            print_page = pdf_page - self.page_diff + 1
            pages[print_page] = page
        return pages

In [27]:
class PageCleaner:
    @staticmethod
    def remove_image_blocks(content):
        content["blocks"] = [b for b in content.get("blocks", []) if b.get("type") == 0]
        return content

    @staticmethod
    def change_rotation(bbox, matrix):
        points = [fitz.Point(*p) * matrix for p in [
            (bbox[0], bbox[1]),
            (bbox[2], bbox[1]),
            (bbox[2], bbox[3]),
            (bbox[0], bbox[3])
        ]]
        xs, ys = zip(*points)
        return min(xs), min(ys), max(xs), max(ys)

    @staticmethod
    def reduce_scattering(content):
        blocks = content.get("blocks", [])
        if not blocks:
            return content

        min_x = min(block['bbox'][0] for block in blocks)
        min_y = min(block['bbox'][1] for block in blocks)

        second_min_x = min((b['bbox'][0] for b in blocks if b['bbox'][0] != min_x), default=min_x)
        second_min_y = min((b['bbox'][1] for b in blocks if b['bbox'][1] != min_y), default=min_y)

        for block in blocks:
            block['bbox'] = PageCleaner._shift_bbox(block['bbox'], second_min_x, second_min_y)
            for line in block.get('lines', []):
                line['bbox'] = PageCleaner._shift_bbox(line['bbox'], second_min_x, second_min_y)
                for span in line.get('spans', []):
                    span['bbox'] = PageCleaner._shift_bbox(span['bbox'], second_min_x, second_min_y)
        return content

    @staticmethod
    def _shift_bbox(bbox, dx, dy):
        x0, y0, x1, y1 = bbox
        return x0 - dx, y0 - dy, x1 - dx, y1 - dy

In [28]:
class LineProcessor:
    @staticmethod
    def process(content, print_page, pdf_page, parameter):
        data = []
        for block in content.get('blocks', []):
            block_type = 'a-block' if print_page % 2 == 0 else 'b-block'
            data.append((*block['bbox'], None, None, block_type, pdf_page, print_page))
            for line in block.get("lines", []):
                # add scip empty lines?
                # ignore lines containing fonts used in Watermarks (maybe move to span level or collect irgnored spans?)
                if any(span['font'] in parameter['ignore_fonts'] for span in line.get('spans', [])):
                    continue
                line_bbox, line_text, is_italic = LineProcessor._process_line(line, print_page, parameter)
                line_type = 'a-line' if print_page % 2 == 0 else 'b-line'
                x_center = (line_bbox[0] + line_bbox[2]) / 2
                y_center = (line_bbox[1] + line_bbox[3]) / 2
                data.append((*line_bbox, x_center, y_center, line_type, pdf_page, print_page, line_text, is_italic))
        return data

    @staticmethod
    def _process_line(line, print_page, parameter):
        i_count = r_count = 0
        line_text = ''
        line_bbox = line['bbox']

        for span in line.get('spans', []):
            # count italic and non italic spans of each line 
            if ('Italic' or 'italic') in span['font']:
                i_count += 1
            else:
                r_count += 1

            # shorten spans and lines that extend beyond the text field due to an error in ocr
            if parameter['compensate_ocr_error']:
                ocr_limit = parameter['ocr_error']['a-page'] if print_page % 2 == 0 else parameter['ocr_error']['b-page']

                if span['bbox'][2] > ocr_limit:
                    sx0, sy0, _, sy1 = span['bbox']
                    span['bbox'] = (sx0, sy0, sx0, sy1) # shorten span (is this even necessery?)

                    lx0, ly0, _, ly1 = line_bbox
                    line_bbox = (lx0, ly0, sx0, ly1) # shorten line
            
            # combine span texts of each line
            line_text += span['text']
        return line_bbox, line_text, i_count > r_count

### Classify paragraphs by line classification
Rule-based classification of individual lines; the page structure allows a hierarchical approach.

In [29]:
class ParagraphClassifier:
    def __init__(self, df, parameter_a, parameter_b):
        self.df = df
        self.parameter_a = parameter_a
        self.parameter_b = parameter_b

        self.classified_text = []
        self.previous_category = None
        self.previous_text = []
        self.i_count = 0
        self.r_count = 0
        self.previous_line_bbox = (0, 0, 0, 0)
        self.pagerange_print = []
        self.pagerange_pdf = []

    # select parameter according to print page
    def get_parameter(self, print_page: int) -> dict:
        return self.parameter_a if (print_page % 2) == 0 else self.parameter_b

    # decide wether a new paragraph begins
    def new_paragraph(self, category: str, x0: float, parameter: dict) -> bool:
        return (
            category != self.previous_category
            or parameter['indentation_start'] < x0 < parameter['indentation_end']
        )

    # append text and classification to classified_text
    def save_paragraph(self):
        if self.previous_category:
            # it may depend on the edition which text is in italics, so it may be necessary to reverse the '>'.
            if self.previous_category == 'other' and self.i_count > self.r_count:
                paragraph_type = 'e-Regestentext'
            else:
                paragraph_type = self.previous_category

            self.classified_text.append({
                'type': paragraph_type,
                'value': ' '.join(self.previous_text)
            })

            self.classified_text.append({
                'type': 'print_page',
                'value': self.pagerange_print
            })
            self.classified_text.append({
                'type': 'pdf_page',
                'value': self.pagerange_pdf
            })

    # line classification
    def classify_line(self, row, previous_line_bbox, parameter):
        width = row['x1'] - row['x0']
        
        if row['y_center'] < parameter['header_border'] and parameter['left_pagenumber_border'] < row['x_center'] < parameter['right_pagenumber_border']:
            return 'header'
        elif row['x_center'] < parameter['left_pagenumber_border'] and (row['y_center'] < parameter['header_border'] or row['y_center'] > parameter['footer_border']):    # left standing page number
            return 'a-page'
        elif row['x_center'] > parameter['right_pagenumber_border'] and (row['y_center'] < parameter['header_border'] or row['y_center'] > parameter['footer_border']):   # right standing page number
            return 'b-page'
        elif row['y_center'] > parameter['footer_border']:
            return 'footer'
        elif width < parameter['number_width'] and parameter['mid_strip_start'] < row['x_center'] < parameter['mid_strip_end']:
            return 'c-Regestennummer'
        elif ((row['x0'] - previous_line_bbox[2] > 40) or (abs(previous_line_bbox[1] - row['y0']) > 10)) and (parameter['date_strip_start'] < row['x_center'] < parameter['date_strip_end']):
            return 'date'
        else:
            return 'other'
        
    # paragraph classification
    def classify_pragraph(self):
        for row in self.df.to_dict('records'):
            parameter = self.get_parameter(row['print_page'])
            category = self.classify_line(row, self.previous_line_bbox, parameter)

            if row['italic']:
                self.i_count += 1
            else:
                self.r_count += 1

            self.pagerange_print.append(row['print_page'])
            self.pagerange_pdf.append(row['pdf_page'])

            if category:
                if self.new_paragraph(category, row['x0'], parameter):
                    self.save_paragraph()

                    self.previous_category = category
                    self.previous_text = [row['line']]
                    self.i_count = 0
                    self.r_count = 0
                    self.pagerange_print = []
                    self.pagerange_pdf = []
                else:
                    self.previous_text.append(row['line'])

                self.previous_line_bbox = (row['x0'], row['y0'], row['x1'], row['y1'])

        # Letzten Absatz speichern
        self.save_paragraph()

        return self.classified_text

In [30]:
class Regesta:
    def __init__(self):
        self.content_raw = {}
        self.content_processed = {}
        self.pages = {}
        self.processed_df = pd.DataFrame()
        self.classified_texts = []
        self.regesta_data = []

    def open(self, parameter):
        processor = PDFProcessor(parameter)
        self.pages = processor.load_pages()
        for print_page, page in self.pages.items():
            self.content_raw[print_page] = page.get_text("dict")

    def collect_fonts(self):
        fonts_found = set()
        for page_content in self.content_raw.values():
            for block in page_content.get("blocks", []):
                for line in block.get("lines", []):
                    for span in line.get("spans", []):
                        fonts_found.add(span['font'])
        return fonts_found
    
    def check_font(self, font):
        for key, page in self.content_processed.items():
            for block in page['blocks']:
                for line in block['lines']:
                    for span in line['spans']:
                        if span['font'] == font:
                            print(key, span['text'])
    
    def print_page_spans(self, page):
        for block in self.content_processed[page]['blocks']:
                for line in block['lines']:
                    for span in line['spans']:
                        print(span['size'], span['flags'], span['font'], span['bbox'], span['text'])


    def preprocess_text(self, parameter):
        fonts_on_pages = self.collect_fonts()
        print("Fonts found in document:")
        for font in fonts_on_pages:
              print(" ", font)
        all_data = []
        for print_page, page in self.pages.items():
            content = page.get_text("dict")
            rotation = page.rotation_matrix if page.rotation else None

            content = PageCleaner.remove_image_blocks(content)

            if rotation:
                for block in content.get("blocks", []):
                    block['bbox'] = PageCleaner.change_rotation(block['bbox'], rotation)
                    for line in block.get("lines", []):
                        line['bbox'] = PageCleaner.change_rotation(line['bbox'], rotation)

            PageCleaner.reduce_scattering(content)

            page_data = LineProcessor.process(content, print_page, page.number + 1, parameter)
            all_data.extend(page_data)

            self.content_processed[print_page] = content

        self.processed_df = pd.DataFrame(all_data, columns=[
            'x0', 'y0', 'x1', 'y1', 'x_center', 'y_center',
            'type', 'pdf_page', 'print_page', 'line', 'italic'
        ])

    def classify_text(self, df, parameter_a, parameter_b):
        classifier = ParagraphClassifier(df, parameter_a, parameter_b)
        self.classified_texts = classifier.classify_pragraph()
        self.build_regesta(self.classified_texts)


    def build_regesta(self, classified_texts):
            regesta = []
            current_regest = {}
            k = {}
            for text in classified_texts:
                if text['type'] == "c-Regestennummer":
                    if current_regest:
                        regesta.append(current_regest)
                    current_regest = {"c-Regestennummer": text['value']}
                    k = {}
                else:
                    key = text['type']
                    if key in current_regest:
                        key1 = key + f'{k[key]}'
                        current_regest[key1] = text['value']
                        k[key] += 1
                    else:
                        current_regest[key] = text['value']
                        k[key] = 10
            if current_regest:
                regesta.append(current_regest)
            
            self.regesta_data = regesta

### Plot
Plots the coordinates of blocks or lines

In [32]:
# function to plot block and line bbox of a page as rectangles
def plot_pagelines(page, df):
    rect_df = df[df['print_page'] == page]

    # create the figure
    fig = go.Figure()

    # ad block and line bbox as rectangles
    for _, row in rect_df.iterrows():
        line_color = "blue" if (row['type'] == 'a-block') or (row['type'] == 'b-block') else "red"
        line_width = 4 if (row['type'] == 'a-block') or (row['type'] == 'b-block') else 2
        fig.add_shape(
            type="rect",
            x0=row['x0'], y0=row['y0'],
            x1=row['x1'], y1=row['y1'],
            line=dict(color = line_color, width = line_width)
        )

    # set limits for the axes
    fig.update_layout(
        xaxis=dict(range=[-100, 500]),
        yaxis=dict(range=[800, -100]),
        width=500,
        height=700
    )

    fig.show()

In [33]:
# function to plot the coordinates of the line corner points. The hover labels show the text of the corresponding line.
def plot_coordinates(df):
    fig = make_subplots(rows=1, cols=3, subplot_titles=('upper left coordinates: (x0, y0)', 
                                                        'midpoints: ((x0+x1)/2, (y0+y1)/2)', 
                                                        'lower right coordinates: (x1, y1)'))

    # upper left coordinates
    fig.add_trace(
        go.Scatter(x=df['x0'], y=df['y0'], mode='markers', marker=dict(color='red'),
                   text= ('S. ' + df['print_page'].astype(str) + ':   ' + df['line'].astype(str)).tolist(), hoverinfo='text', name='(x0, y0)',
                    hovertemplate=
                    "%{text}<br>" +
                    "x: %{x}<br>" +
                    "y: %{y}<extra></extra>"),
        row=1, col=1
    )

    # midpoints
    fig.add_trace(
        go.Scatter(x=df['x_center'], y=df['y_center'], mode='markers', marker=dict(color='green'),
                   text=('S. ' + df['print_page'].astype(str) + ':   ' + df['line'].astype(str)).tolist(), hoverinfo='text', name='((x0+x1)/2, (y0+y1)/2)',
                    hovertemplate=
                    "%{text}<br>" +
                    "x: %{x}<br>" +
                    "y: %{y}<extra></extra>"),
        row=1, col=2
    )

    # lower right coordinates
    fig.add_trace(
        go.Scatter(x=df['x1'], y=df['y1'], mode='markers', marker=dict(color='blue'),
                   text=('S. ' + df['print_page'].astype(str) + ':   ' + df['line'].astype(str)).tolist(), hoverinfo='text', name='(x1, y1)',
                    hovertemplate=
                    "%{text}<br>" +
                    "x: %{x}<br>" +
                    "y: %{y}<extra></extra>"),
        row=1, col=3
    )

    # invert y-axis to reproduce page layout
    fig.update_yaxes(autorange='reversed', row=1, col=1)
    fig.update_yaxes(autorange='reversed', row=1, col=2)
    fig.update_yaxes(autorange='reversed', row=1, col=3)

    fig.update_layout(height=600, width=1400, title_text="Coordinates Plot", showlegend=False)
    fig.show()

### Postprocessing

In [31]:
def postprocessing(df):
    print_columns = [col for col in df if 'print' in col]
    df['Druckseiten'] = df[print_columns].apply(lambda row: sorted([item for sublist in row if isinstance(sublist, list) for item in sublist if not pd.isna(item)]), axis=1)
    df.drop(columns=print_columns, inplace=True)
    df['Druckseiten'] = df['Druckseiten'].apply(lambda x: [f'{min(x)}-{max(x)}'] if len(x) > 1 and min(x) != max(x) else [min(x)] if len(x) > 0 else [])
    df['Druckseiten'] = df['Druckseiten'].apply(lambda x: ', '.join(map(str, x)) if isinstance(x, list) else x)

    pdf_columns = [col for col in df if 'pdf' in col]
    df['PDFSeiten'] = df[pdf_columns].apply(lambda row: sorted([item for sublist in row if isinstance(sublist, list) for item in sublist if not pd.isna(item)]), axis=1)
    df.drop(columns=pdf_columns, inplace=True)
    df['PDFSeiten'] = df['PDFSeiten'].apply(lambda x: [f'{min(x)}-{max(x)}'] if len(x) > 1 and min(x) != max(x) else [min(x)] if len(x) > 0 else [])
    df['PDFSeiten'] = df['PDFSeiten'].apply(lambda x: ', '.join(map(str, x)) if isinstance(x, list) else x)


    seite_columns = [col for col in df if 'page' in col]
    df['Seitenbereich'] = df[seite_columns].astype(str).apply(lambda row: sorted(row.values), axis=1)
    df.drop(columns=seite_columns, inplace=True)
    df['Seitenbereich'] = df['Seitenbereich'].apply(lambda x: [i for i in x if i != 'nan'])

    header_columns = [col for col in df if 'header' in col]
    df['Headerbereich'] = df[header_columns].astype(str).apply(lambda row: sorted(row.values), axis=1)
    df.drop(columns=header_columns, inplace=True)
    df['Headerbereich'] = df['Headerbereich'].apply(lambda x: [i for i in x if i != 'nan'])
    
    return df

# PROCESS

## INPUT

In [34]:
directory = ''
filename = 'PUU_in_Frankreich_NF_8_Paris_I_Markiert.pdf'
parameter = {
    'path': directory + filename,
    'pdf_pages': (205, 230),
    'first_print_page': 208,
    'ignore_fonts': ['Arial', 'Calibri'],
    'compensate_ocr_error': True,
    'ocr_error': {'a-page': 350, 'b-page': 352}
}

regesta = Regesta()
regesta.open(parameter)
regesta.preprocess_text(parameter)

Fonts found in document:
  Times-Roman
  Palatino-BoldItalic
  Times-Italic
  Times-Bold

## Inspect file

In [35]:
regesta.check_font('Palatino-BoldItalic')

215 p
215 44.

In [36]:
regesta.print_page_spans(230)

7.555467128753662 4 Times-Roman (2.637542724609375, -21.759872436523438, 17.484909057617188, -13.346244812011719) 230
7.555467128753662 4 Times-Roman (150.23760986328125, -21.279769897460938, 161.1533203125, -12.866142272949219) Nr.
7.593530178070068 4 Times-Roman (161.15353393554688, -21.279891967773438, 182.68121337890625, -12.866264343261719)  28-29
9.949873924255371 6 Times-Italic (182.70254516601562, -22.88165283203125, 182.70254516601562, -12.431655883789062) zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDC
9.85267448425293 6 Times-Italic (13.437286376953125, 0.0, 262.22100830078125, 10.347915649414062) Verlorenes Mandat (JL —), zitiert in den nachfolgenden
9.85267448425293 6 Times-Italic (276.40374755859375, 0.0, 334.7018127441406, 10.347915649414062) Kardinalsbrie-
9.85267448425293 6 Times-Italic (-0.483001708984375, 11.76019287109375, 17.218994140625, 22.108108520507812) fen:
9.854952812194824 4 Times-Roman (1.19708251953125, 26.343307495117188, 232.90890502929688, 37.31761169433594) - prospectis transscriptis litterarum domini pape
9.85267448425293 6 Times-Italic (232.906005859375, 26.88006591796875, 335.072509765625, 37.22798156738281)  (Petrus von S. Eusta-
9.85267448425293 6 Times-Italic (12.477569580078125, 38.6402587890625, 73.67646789550781, 48.98817443847656) chius, Nr. 58)
9.854952812194824 4 Times-Roman (1.197509765625, 49.86332702636719, 311.5213317871094, 60.83763122558594) - cum ex mandato domini pape et consilio nostro redire uoluerit
9.85267448425293 6 Times-Italic (311.4828796386719, 50.40008544921875, 337.6287536621094, 60.74800109863281)  (id.,
9.85267448425293 6 Times-Italic (12.4791259765625, 61.91998291015625, 44.63818359375, 72.26789855957031) Nr. 59)
9.854952812194824 4 Times-Roman (1.199066162109375, 72.90312194824219, 336.25506591796875, 83.87742614746094) - quem dominus papa de scholis ad seruitium Romane curie reuocare
9.854952812194824 4 Times-Roman (11.999114990234375, 84.42344665527344, 52.27970886230469, 95.39775085449219) disposuit
9.85267448425293 6 Times-Italic (52.24205017089844, 84.960205078125, 111.59710693359375, 95.30812072753906)  (id., Nr. 60)
9.854952812194824 4 Times-Roman (1.19903564453125, 96.90312194824219, 336.8078918457031, 107.87742614746094) - quem dominus papa, ut ad maiora prouehatur, cum fratribus suis
9.854952812194824 4 Times-Roman (11.998687744140625, 108.42344665527344, 150.17233276367188, 119.39775085449219) reuocare unanimiter disposuit
9.85267448425293 6 Times-Italic (150.13504028320312, 108.960205078125, 283.4385986328125, 119.30812072753906)  (Gregor von Sabina, Nr. 62)
9.854952812194824 4 Times-Roman (1.199554443359375, 120.18327331542969, 334.89385986328125, 131.15757751464844) - a domino papa euocato et apostolicis etiam scriptis ut repedaret am-
9.854952812194824 4 Times-Roman (12.00018310546875, 131.70359802246094, 43.29119873046875, 142.6779022216797) monito
9.85267448425293 6 Times-Italic (43.244293212890625, 132.24037170410156, 132.9588623046875, 142.58827209472656)  (Oktavian, Nr. 65)
9.854952812194824 4 Times-Roman (1.440643310546875, 143.70359802246094, 189.30215454101562, 154.6779022216797) - quem dominus papa ad se uenire iubet
9.85267448425293 6 Times-Italic (189.2789306640625, 144.24037170410156, 337.8525695800781, 154.58827209472656)  (Odo von S. Nicolaus in carcere,
9.85267448425293 6 Times-Italic (12.960906982421875, 155.76026916503906, 44.880126953125, 166.10816955566406) Nr. 68)
9.854952812194824 4 Times-Roman (1.4409637451171875, 166.9833221435547, 284.0703430175781, 177.95762634277344) - a domino papa et tota curia ad hoc ut ordinetur reuocato
9.85267448425293 6 Times-Italic (284.0531311035156, 167.5200958251953, 337.786376953125, 177.8679962158203)  (Petrus de
9.85267448425293 6 Times-Italic (12.9608154296875, 179.04078674316406, 77.53118896484375, 189.38868713378906) Bono, Nr. 70).
9.85267448425293 6 Times-Italic (13.44085693359375, 195.3602752685547, 335.1384582519531, 205.7081756591797) Terminus ante für die nachfolgenden Briefe Nr. 58-70, alle die Rückberu-
9.85267448425293 6 Times-Italic (0.0, 206.8801727294922, 337.3294372558594, 217.2280731201172) fung des römischen Subdiakons Alexius an die Kurie betreffend, ist der Tod
9.85267448425293 6 Times-Italic (2.6407470703125, 218.4000701904297, 117.17788696289062, 228.7479705810547) Hadrians IV. 1159 Sept.l.
9.85267448425293 6 Times-Italic (125.99978637695312, 218.4000701904297, 174.41796875, 228.7479705810547) Die Angabe
9.854952812194824 4 Times-Roman (174.417236328125, 217.86329650878906, 265.0838317871094, 228.8376007080078)  in proxima hieme
9.85267448425293 6 Times-Italic (265.0516662597656, 218.4000701904297, 337.5521545410156, 228.7479705810547)  (Nr. 58) deutet
9.85267448425293 6 Times-Italic (2.16046142578125, 229.9199676513672, 88.34835815429688, 240.2678680419922) auf einen nicht viel
9.85267448425293 6 Times-Italic (86.85771179199219, 229.9199676513672, 334.8778076171875, 240.2678680419922) früheren Zeitpunkt. Die Briefe Nr. 62 und Nr. 69 erwäh-
9.85267448425293 6 Times-Italic (2.161773681640625, 241.4398651123047, 337.7736511230469, 251.7877655029297) nen Rückkehr des Alexius nach Rom selbst, während Hadrian IV. bereits
9.85267448425293 6 Times-Italic (2.160919189453125, 252.9601593017578, 307.7131652832031, 263.3080596923828) am 26.-27. Mai 1159 Rom verließ und nach Tusculum bzw. Anagni
9.85267448425293 6 Times-Italic (315.60687255859375, 252.9601593017578, 337.94207763671875, 263.3080596923828) ging.
9.85267448425293 6 Times-Italic (2.15997314453125, 264.4800567626953, 94.34716796875, 274.8279571533203) Eine Schlußfolgerung
9.85267448425293 6 Times-Italic (104.160400390625, 264.4800567626953, 295.92938232421875, 274.8279571533203) daraus, unsere Schreiben müßten vor dem
9.902310371398926 6 Times-Italic (295.93255615234375, 264.4800262451172, 315.2530517578125, 274.8279266357422)  27.
9.85267448425293 6 Times-Italic (315.2525329589844, 264.4800262451172, 338.0279541015625, 274.8279266357422)  Mai
9.85267448425293 6 Times-Italic (2.397674560546875, 275.9999237060547, 335.3951721191406, 286.3478240966797) liegen, wäre jedoch zu unsicher. Geraume Zeit muß seit dem Tod des Bi-
9.85267448425293 6 Times-Italic (1.917938232421875, 287.5198211669922, 286.3273620605469, 297.8677215576172) schofs Theobald von Paris 1159 Jan. 8 vergangen sein (Nr. 70).
9.85267448425293 6 Times-Italic (13.198043823242188, 300.9600067138672, 337.6506652832031, 311.3079071044922) Der Hinweis auf die künftige Erhebung zum Kardinal steht nur in den
9.85267448425293 6 Times-Italic (2.397674560546875, 312.4799041748047, 172.46762084960938, 322.8278045654297) Briefen der Verwandten des Alexius, d.
9.902310371398926 6 Times-Italic (172.46755981445312, 312.4800262451172, 182.53298950195312, 322.8279266357422)  h.
9.85267448425293 6 Times-Italic (182.53253173828125, 312.4800262451172, 335.76666259765625, 322.8279266357422)  des Petrus von S. Eustachius, Gre-
9.85267448425293 6 Times-Italic (2.157135009765625, 323.9999237060547, 336.8279113769531, 334.3478240966797) gor von Sabina und Petrus de Bono. Der Papst dürfte sich auf die Formel
9.854952812194824 4 Times-Roman (2.15692138671875, 334.98304748535156, 134.15399169921875, 345.9573516845703) ad seruitium Romane curie
9.85267448425293 6 Times-Italic (134.1358642578125, 335.5198211669922, 187.05075073242188, 345.8677215576172)  beschränkt
9.85267448425293 6 Times-Italic (195.11358642578125, 335.5198211669922, 271.457763671875, 345.8677215576172) haben. Oktavian,
9.85267448425293 6 Times-Italic (279.5948181152344, 335.5198211669922, 295.1136169433594, 345.8677215576172) der
9.85267448425293 6 Times-Italic (303.85235595703125, 335.5198211669922, 337.9039306640625, 345.8677215576172) künftige
9.85267448425293 6 Times-Italic (2.87689208984375, 347.0401153564453, 335.37310791015625, 357.3880157470703) Gegner Alexanders III. (Nr. 65), erwähnt die Erhebung indirekt. Der Kanz-
9.85267448425293 6 Times-Italic (2.63800048828125, 358.5600128173828, 194.2774658203125, 368.9079132080078) ler Roland dagegen schreibt eher reserviert:
9.854952812194824 4 Times-Roman (194.24972534179688, 358.0232391357422, 336.827392578125, 368.99754333496094)  ad propria desiderat remeare
9.85267448425293 6 Times-Italic (2.87835693359375, 370.0799102783203, 41.767913818359375, 380.4278106689453) (Nr. 66).
9.85267448425293 6 Times-Italic (14.158462524414062, 383.0401153564453, 338.35662841796875, 393.3880157470703) Wir stellen im folgenden die Briefe des Petrus von S. Eustachius als die
9.85267448425293 6 Times-Italic (2.6392822265625, 394.5600128173828, 269.8170166015625, 404.9079132080078) des eigentlichen Promotors der Sache voran. Die übrigen
9.85267448425293 6 Times-Italic (281.660400390625, 394.5600128173828, 336.1275329589844, 404.9079132080078) Empfehlungs-
9.85267448425293 6 Times-Italic (2.39862060546875, 406.0799102783203, 237.890869140625, 416.4278106689453) schreiben folgen nach der Hierarchie der Aussteller.
9.949873924255371 20 Times-Bold (244.53097534179688, 405.1282501220703, 244.53097534179688, 416.41822814941406) xvutsrqponmlihgfedcbaXVUSROLHECA
9.855061531066895 20 Times-Bold (162.71847534179688, 445.29627990722656, 177.77767944335938, 456.47865295410156) 58.
9.85267448425293 6 Times-Italic (13.19879150390625, 469.6798858642578, 77.70826721191406, 480.0277862548828) Kardinaldiakon
9.85267448425293 6 Times-Italic (87.59963989257812, 469.6798858642578, 335.39227294921875, 480.0277862548828) P(etrus) von S. Eustachius empfiehlt dem (in Paris) stu-
9.85267448425293 6 Times-Italic (2.15899658203125, 481.4401397705078, 231.47824096679688, 491.7880401611328) dierenden Subdiakon der römischen Kirche A(lexius)
9.902310371398926 6 Times-Italic (231.44955444335938, 481.4400177001953, 248.55975341796875, 491.7879180908203)  —
9.85267448425293 6 Times-Italic (248.56155395507812, 481.4400177001953, 337.2347412109375, 491.7879180908203)  anschließend an ei-
9.85267448425293 6 Times-Italic (2.39776611328125, 493.19984436035156, 276.42572021484375, 503.54774475097656) nen Familienrat und beiliegende Papst- und Kardinalsbriefe
9.85267448425293 6 Times-Italic (286.31707763671875, 493.19984436035156, 335.3753662109375, 503.54774475097656) — den Ab-
9.85267448425293 6 Times-Italic (1.918121337890625, 504.9600372314453, 219.461181640625, 515.3079376220703) schluß seiner Philosophie- und Theologiestudien
9.85267448425293 6 Times-Italic (228.71701049804688, 504.9600372314453, 316.65411376953125, 515.3079376220703) sowie die Rückkehr
9.85267448425293 6 Times-Italic (325.411865234375, 504.9600372314453, 337.6787414550781, 515.3079376220703) im
9.85267448425293 6 Times-Italic (2.15826416015625, 516.7198028564453, 51.430938720703125, 527.0677032470703) kommenden
9.85267448425293 6 Times-Italic (60.718414306640625, 516.7198028564453, 260.9211730957031, 527.0677032470703) Winter entweder in Begleitung des Abtes von
9.85267448425293 6 Times-Italic (270.28009033203125, 516.7198028564453, 335.6468811035156, 527.0677032470703) St-Germain-des-
9.85267448425293 6 Times-Italic (2.6385040283203125, 528.4799957275391, 125.04409790039062, 538.8278961181641) Prés oder mit anderer Hilfe.
9.85267448425293 6 Times-Italic (220.55654907226562, 528.4799957275391, 327.60650634765625, 538.8278961181641) (1159 vor September 1).

## Plot

In [37]:
page = 230 # page refers to the printed page number

page_difference = parameter['pdf_pages'][0]-parameter['first_print_page']
print('available pages (print):', f"({parameter['pdf_pages'][0]-page_difference}, {parameter['pdf_pages'][1]-page_difference})")
print('available pages (PDF):  ', parameter['pdf_pages'])

plot_pagelines(page, regesta.processed_df)

available pages (print): (208, 233)
available pages (PDF):   (205, 230)

In [38]:
# adjust input to display: type == a-block and b-block for blocks, a-line and b-line for lines
vdf = regesta.processed_df[regesta.processed_df['type']=='b-line']
vdf = regesta.processed_df[regesta.processed_df['type']=='a-line']
#vdf = regesta.processed_df[(regesta.processed_df['type']=='a-line')|(regesta.processed_df['type']=='b-line')]
#vdf = vdf[(210 < vdf['print_page'])&(vdf['print_page'] < 220)]
#vdf = vdf[vdf['print_page']==277]

plot_coordinates(vdf)

## SET PAGE REGION LIMITS
Use the plots to define boundaries for page regions on even (a) and odd (b) pages

In [39]:


# a = even page number
# b = odd page number

parameter_a = {
    'header_border' : 0,               # everything above (midpoints)
    'footer_border' : 560,               # everything below (midpoints)
    
    'left_pagenumber_border' : 20,        # everything left to (to exclude set to 0)
    'right_pagenumber_border' : 340,     # everything right to (to exclude set to a value greater than the page width)
    
    'indentation_start' : 10,           # everything between start and end (left border)
    'indentation_end' : 15,
    
    'mid_strip_start' : 163,             # everything between start and end (midpoints)
    'mid_strip_end' : 171,
    
    'date_strip_start' : 230,            # everything between start and end (midpoints)
    'date_strip_end' : 315,
    
    'number_width' : 26                  # maximal width of a regesta number
}

parameter_b = {
    'header_border' : 0,               # everything above (midpoints)
    'footer_border' : 580,               # everything below (midpoints)
    
    'left_pagenumber_border' : 300,      # everything left to (to exclude set to 0)
    'right_pagenumber_border' : 410,     # everything right to (to exclude set to a value greater than the page width)

    'indentation_start' : 10,           # everything between start and end (left border)
    'indentation_end' : 15,
    
    'mid_strip_start' : 165,             # everything between start and end (midpoints)
    'mid_strip_end' : 171,

    'date_strip_start' : 210,            # everything between start and end (midpoints)
    'date_strip_end' : 325,
    
    'number_width' : 26                  # maximal width of a regesta number
}

In [40]:
# show data to store them below
print(f'#{filename}')
print(f'#parameter = {parameter}')
print(f'#parameter_a = {parameter_a}')
print(f'#parameter_b = {parameter_b}')

#PUU_in_Frankreich_NF_8_Paris_I_Markiert.pdf
#parameter = {'path': 'PUU_in_Frankreich_NF_8_Paris_I_Markiert.pdf', 'pdf_pages': (205, 230), 'first_print_page': 208, 'ignore_fonts': ['Arial', 'Calibri'], 'compensate_ocr_error': True, 'ocr_error': {'a-page': 350, 'b-page': 352}}
#parameter_a = {'header_border': 0, 'footer_border': 560, 'left_pagenumber_border': 20, 'right_pagenumber_border': 340, 'indentation_start': 10, 'indentation_end': 15, 'mid_strip_start': 163, 'mid_strip_end': 171, 'date_strip_start': 230, 'date_strip_end': 315, 'number_width': 26}
#parameter_b = {'header_border': 0, 'footer_border': 580, 'left_pagenumber_border': 300, 'right_pagenumber_border': 410, 'indentation_start': 10, 'indentation_end': 15, 'mid_strip_start': 165, 'mid_strip_end': 171, 'date_strip_start': 210, 'date_strip_end': 325, 'number_width': 26}

In [41]:
#PUU_in_Frankreich_NF_8_Paris_I_Markiert.pdf
#parameter = {'path': 'PUU_in_Frankreich_NF_8_Paris_I_Markiert.pdf', 'pdf_pages': (205, 230), 'first_print_page': 208, 'ignore_fonts': ['Arial', 'Calibri'], 'compensate_ocr_error': True, 'ocr_error': {'a-page': 350, 'b-page': 352}}
#parameter_a = {'header_border': 0, 'footer_border': 560, 'left_pagenumber_border': 20, 'right_pagenumber_border': 340, 'indentation_start': 10, 'indentation_end': 15, 'mid_strip_start': 163, 'mid_strip_end': 171, 'date_strip_start': 230, 'date_strip_end': 315, 'number_width': 26}
#parameter_b = {'header_border': 0, 'footer_border': 580, 'left_pagenumber_border': 300, 'right_pagenumber_border': 410, 'indentation_start': 10, 'indentation_end': 15, 'mid_strip_start': 165, 'mid_strip_end': 171, 'date_strip_start': 210, 'date_strip_end': 325, 'number_width': 26}

#PUU_in_Frankreich_NF_9_Paris_II_Markiert.pdf     (175, 216) First page: 177
#parameter_a = {'header_border': 10, 'footer_border': 570, 'left_pagenumber_border': 0, 'right_pagenumber_border': 320, 'indentation_start': 10, 'indentation_end': 14, 'mid_strip_start': 165, 'mid_strip_end': 172, 'date_strip_start': 200, 'date_strip_end': 315, 'number_width': 30}
#parameter_b = {'header_border': 10, 'footer_border': 570, 'left_pagenumber_border': 12, 'right_pagenumber_border': 320, 'indentation_start': 10, 'indentation_end': 15, 'mid_strip_start': 165, 'mid_strip_end': 172, 'date_strip_start': 200, 'date_strip_end': 325, 'number_width': 30}
#compensate_ocr_error = False

## MAIN - EXTRACT DATA

### Classify text and sort text into regesta

In [42]:
extract_df = regesta.processed_df[regesta.processed_df['type'].isin(['a-line', 'b-line'])]
regesta.classify_text(extract_df, parameter_a, parameter_b)

#for regest in regesta.regesta_data[0:2]:
#    print(regest)

### Postprocessing (rearange columns, join page numbers...)

In [43]:
# show regesta as table (DataFrame)
export_df = pd.DataFrame(regesta.regesta_data)
export_df_sorted = export_df.sort_index(axis=1)

export_df_sorted

,a-page,a-page10,c-Regestennummer,date,date10,e-Regestentext,e-Regestentext10,e-Regestentext11,e-Regestentext12,e-Regestentext13,...,print_page26,print_page27,print_page28,print_page29,print_page30,print_page31,print_page32,print_page33,print_page34,print_page35
0,208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nr. 32-33,210,40.,"Ferentino, 1150 Dezember 17.",liano ss.,Eugen III. bestätigt dem Abt Odo von Ste-Genev...,"Chartular s. XIII: Bibl. Ste-Geneviève, ms. 35...",Das Privileg ist gegenüber den voraufgehenden ...,a> imperpetuurr»zyxwvutsrqponmlkjihgfedcbaZYXW...,2) propheta zur Bezeichnung des Psalmisten sc...,...,[210],"[210, 210, 210]","[210, 210]",[210],"[210, 210]",[210],"[210, 210, 210, 210]",NaN,NaN,NaN
2,Nr. 32-33,NaN,41.,NaN,NaN,Eugen III. bestätigt dem Bischof Theobald von ...,Orig. aus dem Archiv des Bischofs von Paris: A...,fang 1150 noch nicht definitiv abgeschlossen. ...,Die umstrittene Pfarrkirche war St-Jean-du-Mon...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,212,NaN,III.).,NaN,NaN,2) Gemeint die Diener der Säkularkanoniker; v...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nr. 3 2 - 3 3,NaN,42.,"Rom, St. Peter (1150. 53) Mai 3.",NaN,Eugen III. bestätigt dem Abt G(ilduin) von St-...,"Orig.: Arch. Nat., S 2156 B n.37 [AJ. - Annale...",Auf die Präbende und die Annaten in Montlhéry...,') Urkunde des Abtes Johannes von Montlhéry bi...,2) Urkunde des Erzbischofs Hugo von Sens bish...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,214,Nr. 32-33,43.,"Lateran, 1154 Januar 1.",ss.,Anastasius IV. bestätigt der Abtei St-Victor/P...,"Orig.: Arch. Nat., L 229 I n. 5 [A]. — Chartul...","minice anno M°.C°.L°.III°, pontificatus uero d...","') Urkunde König Ludwigs VII. (1151-53), nich...","2) Urkunde Erzbischofs Hugo von Sens, Orig.: A...",...,"[215, 215]","[215, 215, 215, 215, 215, 215, 215, 215]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,216,NaN,44.,"Lateran, (1154) Januar 2.",NaN,Anastasius IV. bestätigt der Abtei St-Victor/P...,"Orig.: Arch. Nat., L 229 In.6[AJ.- Chartular ...",Zu den einzelnen Besitzeinheiten vgl. vor all...,*`> Das Datum von anderer Hand nachgetragen A.,') Urkunde des Bischofs Manasse von Orléans b...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Nr. 32-33,NaN,45.,"Lateran, 1154 (April 20 oder Mai 9).",NaN,Anastasius IV. bestätigt der Abtei (Ste-Genevi...,Archivinventar s. XVII von Ste-Geneviève: Arch...,Ähnlich wie die wichtige Bestätigung der Refo...,"Datum Laterani, 12°. idus c ) maii, anno 1154,...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,218,NaN,46.,(Ende 1153 -vor Sommer,NaN,"Simon (von Saint-Denis, ehemaliger Kanzler Kö...",1154).,Kopie s. XIII aus verlorener Briefsammlung vo...,Die Vorgeschichte dieses und des folgenden Br...,') Brief Anastasius' IV. nicht erhalten.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Nr. 47,220,47.,(1154 Sommer).,NaN,Si(mon von Saint-Denis) berichtet dem Kardina...,Kopie s. XVII aus verlorener Briefsammlung vo...,"Das Jahr 1154 ergibt sich aus Nr. 46, der Somm...",gen Simon am Königshof nicht weiter gegangen u...,Die Überlieferung der beiden Briefe Simons in ...,...,"[220, 220]",[220],[220],"[220, 220, 220, 220, 220]",[220],"[220, 220]",[220],"[220, 220, 220, 220, 220, 220]","[220, 220]","[220, 220]"
10,Nr. 32-33,NaN,48.,"Lateran, (1154) November 25.",NaN,Anastasius IV. bestätigt der Abtei St-Victor/P...,"Orig.: Arch. Nat., L 229 I n. 4 [AJ. - Chartul...",Die Abmachungen zeigen erneut den wirtschaftl...,') Urkunde des Abtes von St-Séverín in Châtea...,2) Vertrag mit Longpont betr. Montlhéry: Urku...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,222,NaN,49.,NaN,NaN,Hadrian IV. bestätigt der Abtei St-Victor/Pari...,"Orig.: Arch. Nat., L 229 II n. 1 [AJ. — Annale...",Wörtliche Wiederholung der nur 18 Tage älteren...,"Oktober 25, auf dem auch zwei zugehörige Urkun...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Nr. 32-33,NaN,50.,"Rom St. Peter, (1154) Dezember 16.",NaN,Hadrian IV. bestätigt dem Bischof Theobald von...,Orig. aus dem Archiv des Bischofs von Paris: A...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,224,NaN,51.,(1155 Anfang).,NaN,Der römische Konsul Grat(ianus) Pierleone dank...,Kopien s. XVI-XVII aus verlorener Briefsammlu...,Den Abt Gilduin als Empfänger hat allein Jean ...,Als Empfänger nahmen Deniße und nach ihm Class...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Nr. 32-33,NaN,52.,"Lateran, (1156-58) Dezember 23.",NaN,Hadrian IV. gewährt dem Abt Achardus und den K...,"Orig.: Arch. Nat., L 229 II n. 10 [A]. - Chart...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,226,NaN,53. zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLK...,"Lateran, (1159) Februar 18.",NaN,Hadrian IV. bestätigt dem Abt Achardus und den...,"Orig.: Arch. Nat., L 906 n. 25 [AJ. - Chartula...",Das Jahr 1159 ergibt sich aus dem großen Privi...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,54. zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLK...,"Lateran, (1159) Februar 18.",NaN,Hadrian IV. befiehlt dem Abt und den Brüdern v...,Orig. aus dem Archiv von St-Victor: Arch. Nat....,*`> Datum von anderer Hand A. b ] Butle beili...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Nr. 32-33,NaN,55.,"Lateran, (1159) Mai 23.",NaN,Hadrian IV. bestätigt dem Abt Achardus und den...,"Orig.: Arch. Nat., L 229 II n. 18 [A], - Chart...","(8. Scrinium). — Ed.: Châtillon, Theologie d`A...",Eine gleichlautende Verfügung erging am 27. M...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,228,Nr. 32-33,56.,(1159 Jan. 6-Sept.,NaN,Der päpstliche Kaplan Petrus entbietet dem Abt...,1).,Kopien s. XVII aus verlorener Briefsammlung v...,Der Brief ist in mehrfacher Weise aufschlußrei...,Die erwähnten finanziellen Transaktionen blei...,...,"[229, 229, 229, 229, 229]","[229, 229, 229, 229, 229, 229, 229]","[229, 229, 229, 229, 229, 229, 229, 229, 229, ...","[229, 229]","[229, 229]","[229, 229, 229, 229, 229, 229, 229, 229, 229, ...","[229, 229, 229]",[229],"[229, 229]","[229, 229, 229, 229]"
19,230,NaN,57.,(1159 vor September 1).,NaN,Papst (Hadrian IV.) befiehlt seinem Subdiakon ...,"Verlorenes Mandat (JL —), zitiert in den nachf...","Bono, Nr. 70).",Terminus ante für die nachfolgenden Briefe Nr....,Der Hinweis auf die künftige Erhebung zum Kard...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Nr. 32-33,NaN,58.,(1159 vor September 1).,NaN,Kardinaldiakon P(etrus) von S. Eustachius emp...,Kopie s. XVII aus verlorener Briefsammlung vo...,Die Emendation O. > A. für den Empfänger (Anm...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,232,NaN,59.,(1159 vor September 1).,NaN,Kardinaldiakon (Petrus) von S. Eustachius eri...,Kopie s. XVII aus verlorener Briefsammlung vo...,Der Bezug auf Alexius ergibt sich durch seine ...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Nr. 32-33,NaN,60.,(1159 vor September 1).,NaN,Kardinaldiakon (Petrus) von S. Eustachius bit...,Kopie s. XVII aus verlorener Briefsammlung vo...,') Abt Odo II. von St-Denis 1151-62.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,61.,NaN,NaN,Gleichlautender Bittbrief desselben Kardinals ...,Datum und Überlieferung wie Nr. 60. Der Gruß a...,'`> adempto G `. b`> folgt A gestrichen G4.,') Abt Ansold von St-Corneille in Compiègne ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,62.,(1159 vor September 1).,NaN,Nach einstimmigem Beschluß des Papstes (Hadria...,Kopien s. XVII aus verlorener Briefsammlung v...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
# group page numbers and headers in new columns
export_df_reorderd = postprocessing(export_df_sorted)
export_df_reorderd

,c-Regestennummer,date,date10,e-Regestentext,e-Regestentext10,e-Regestentext11,e-Regestentext12,e-Regestentext13,e-Regestentext14,e-Regestentext15,...,other12,other13,other14,other15,other16,other17,Druckseiten,PDFSeiten,Seitenbereich,Headerbereich
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,208,205,[208 ],[Nr. 28-29 ]
1,40.,"Ferentino, 1150 Dezember 17.",liano ss.,Eugen III. bestätigt dem Abt Odo von Ste-Genev...,"Chartular s. XIII: Bibl. Ste-Geneviève, ms. 35...",Das Privileg ist gegenüber den voraufgehenden ...,a> imperpetuurr»zyxwvutsrqponmlkjihgfedcbaZYXW...,2) propheta zur Bezeichnung des Psalmisten sc...,"3) 2 Tim. 2,19; Rom. 11,29.",4 ) Vgl. oben Nr. 31 (1148 Okt. 20).,...,EgoA> Iohannes Paparo'• diac. card. sancti Adr...,† Ego Iohannes diac. card.*' sanete Marie noue...,Dat. Ferentini per manum Bosonis sanete Romane...,"») Prov. 3,19; Ps. 23,2.","') Vgl. Robert II. (Lasteyrie p.109 n.79), Hei...",NaN,208-210,205-207,"[210 , Nr. 32-33 ]","[2 0 9 , Nr. 28-29 ]"
2,41.,NaN,NaN,Eugen III. bestätigt dem Bischof Theobald von ...,Orig. aus dem Archiv des Bischofs von Paris: A...,fang 1150 noch nicht definitiv abgeschlossen. ...,Die umstrittene Pfarrkirche war St-Jean-du-Mon...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,210-211,207-208,[Nr. 32-33 ],[211 zyxwvutsrqponmlkjihgfedcbaZYXWVUT]
3,III.).,NaN,NaN,2) Gemeint die Diener der Säkularkanoniker; v...,NaN,NaN,NaN,NaN,NaN,NaN,...,') Gemeint die Regularkanoniker; vgl. weiter ...,NaN,NaN,NaN,NaN,NaN,211-212,208-209,[212 ],[Nr. 28-29 ]
4,42.,"Rom, St. Peter (1150. 53) Mai 3.",NaN,Eugen III. bestätigt dem Abt G(ilduin) von St-...,"Orig.: Arch. Nat., S 2156 B n.37 [AJ. - Annale...",Auf die Präbende und die Annaten in Montlhéry...,') Urkunde des Abtes Johannes von Montlhéry bi...,2) Urkunde des Erzbischofs Hugo von Sens bish...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,212-213,209-210,[Nr. 3 2 - 3 3 ],[213 ]
5,43.,"Lateran, 1154 Januar 1.",ss.,Anastasius IV. bestätigt der Abtei St-Victor/P...,"Orig.: Arch. Nat., L 229 I n. 5 [A]. — Chartul...","minice anno M°.C°.L°.III°, pontificatus uero d...","') Urkunde König Ludwigs VII. (1151-53), nich...","2) Urkunde Erzbischofs Hugo von Sens, Orig.: A...",y) Gemeint zwei Urkunden: Nr. 21 (1144 März) u...,J ) Urkunden betr. Wasserrechte an der Bièvre ...,...,† Ego Henricus presb. card. tit. sanctorum Ner...,Dat. Lat(erani) per manum Rolandi sancte Roman...,NaN,NaN,NaN,NaN,213-215,210-212,"[214 , Nr. 32-33 ]","[215 , Nr. 28-29 ]"
6,44.,"Lateran, (1154) Januar 2.",NaN,Anastasius IV. bestätigt der Abtei St-Victor/P...,"Orig.: Arch. Nat., L 229 In.6[AJ.- Chartular ...",Zu den einzelnen Besitzeinheiten vgl. vor all...,*`> Das Datum von anderer Hand nachgetragen A.,') Urkunde des Bischofs Manasse von Orléans b...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,215-216,212-213,[216 ],[Nr. 28-29 ]
7,45.,"Lateran, 1154 (April 20 oder Mai 9).",NaN,Anastasius IV. bestätigt der Abtei (Ste-Genevi...,Archivinventar s. XVII von Ste-Geneviève: Arch...,Ähnlich wie die wichtige Bestätigung der Refo...,"Datum Laterani, 12°. idus c ) maii, anno 1154,...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,216-217,213-214,[Nr. 32-33 ],[217 ]
8,46.,(Ende 1153 -vor Sommer,NaN,"Simon (von Saint-Denis, ehemaliger Kanzler Kö...",1154).,Kopie s. XIII aus verlorener Briefsammlung vo...,Die Vorgeschichte dieses und des folgenden Br...,') Brief Anastasius' IV. nicht erhalten.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,217-218,214-215,[218 ],[Nr. 46-47 ]
9,47.,(1154 Sommer).,NaN,Si(mon von Saint-Denis) berichtet dem Kardina...,Kopie s. XVII aus verlorener Briefsammlung vo...,"Das Jahr 1154 ergibt sich aus Nr. 46, der Somm...",gen Simon am Königshof nicht weiter gegangen u...,Die Überlieferung der beiden Briefe Simons in ...,') Näheres über diese Leistungen des Simon im...,"2) Luc. 1, 78; Col. 3.12.",...,') Bischof Theobald von Paris (1144-1159).,"º) cf. Johannes von Salisbury, Hist. pont. c....",12) Antwort des Kardinals an Simon nicht beka...,NaN,NaN,NaN,218-220,215-217,"[220 , Nr. 47 ]","[219 zyxwvutsrqponmlkjihgfedcbaZYXWV, Nr. 28-29 ]"
10,48.,"Lateran, (1154) November 25.",NaN,Anastasius IV. bestätigt der Abtei St-Victor/P...,"Orig.: Arch. Nat., L 229 I n. 4 [AJ. - Chartul...",Die Abmachungen zeigen erneut den wirtschaftl...,') Urkunde des Abtes von St-Séverín in Châtea...,2) Vertrag mit Longpont betr. Montlhéry: Urku...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,220-221,217-218,[Nr. 32-33 ],[221 ]
11,49.,NaN,NaN,Hadrian IV. bestätigt der Abtei St-Victor/Pari...,"Orig.: Arch. Nat., L 229 II n. 1 [AJ. — Annale...",Wörtliche Wiederholung der nur 18 Tage älteren...,"Oktober 25, auf dem auch zwei zugehörige Urkun...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,221-222,218-219,[222 ],[Nr. 28-29 zyxwvutsrqponmlkjihgfedcbaZYXWVUTSR...
12,50.,"Rom St. Peter, (1154) Dezember 16.",NaN,Hadrian IV. bestätigt dem Bischof Theobald von...,Orig. aus dem Archiv des Bischofs von Paris: A...,NaN,NaN,NaN,NaN,NaN,...,') Eugen III. (1149) Febr. 25 (Nr. 34). xvutsr...,NaN,NaN,NaN,NaN,NaN,222-223,219-220,[Nr. 32-33 ],[223 ]
13,51.,(1155 Anfang).,NaN,Der römische Konsul Grat(ianus) Pierleone dank...,Kopien s. XVI-XVII aus verlorener Briefsammlu...,Den Abt Gilduin als Empfänger hat allein Jean ...,Als Empfänger nahmen Deniße und nach ihm Class...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,223-224,220-221,[224 ],[Nr. 28-29 ]
14,52.,"Lateran, (1156-58) Dezember 23.",NaN,Hadrian IV. gewährt dem Abt Achardus und den K...,"Orig.: Arch. Nat., L 229 II n. 10 [A]. - Chart...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,224-225,221-222,[Nr. 32-33 ],[225 xvutsrqponmlihgfedcbaXVUSROLH]
15,53. zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLK...,"Lateran, (1159) Februar 18.",NaN,Hadrian IV. bestätigt dem Abt Achardus und den...,"Orig.: Arch. Nat., L 906 n. 25 [AJ. - Chartula...",Das Jahr 1159 ergibt sich aus dem großen Privi...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,225-226,222-223,[226 ],[Nr. 28-29 xvutsrqponmlihgfedcbaXVUSROLHECA]
16,54. zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLK...,"Lateran, (1159) Februar 18.",NaN,Hadrian IV. befiehlt dem Abt und den Brüdern v...,Orig. aus dem Archiv von St-Victor: Arch. Nat....,*`> Datum von anderer Hand A. b ] Butle beili...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,226,223,[],[]
17,55.,"Lateran, (1159) Mai 23.",NaN,Hadrian IV. bestätigt dem Abt Achardus und den...,"Orig.: Arch. Nat., L 229 II n. 18 [A], - Chart...","(8. Scrinium). — Ed.: Châtillon, Theologie d`A...",Eine gleichlautende Verfügung erging am 27. M...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,226-227,223-224,[Nr. 32-33 ],[227 zyxwvutsrqponmlkjihgfedcbaZYXWVUT]
18,56.,(1159 Jan. 6-Sept.,NaN,Der päpstliche Kaplan Petrus entbietet dem Abt...,1).,Kopien s. XVII aus verlorener Briefsammlung v...,Der Brief ist in mehrfacher Weise aufschlußrei...,Die erwähnten finanziellen Transaktionen blei...,"Am Schluß scheint Petrus den Wunsch zu äußern,...",') Brief Hadrians IV. an Abt Achardus nicht e...,...,"mulauit, rogo ut inde'> curam quantam poteris ...","Frater Hu. s ), Alcurtensis prior 5), peracto ...",Electi Suessionensis 7) noua dominus papa cupe...,"Mihi placeret c ), quatenus domino pape preces...","""> AcardozyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQP...",') Hugo von Champfleury; vgl. Vorbemerkung. ...,227-229,224-226,"[228 , Nr. 32-33 ]","[229 , Nr. 28-29 zyxwvutsrqponmlkjihgfedcbaZYX..."
19,57.,(1159 vor September 1).,NaN,Papst (Hadrian IV.) befiehlt seinem Subdiakon ...,"Verlorenes Mandat (JL —), zitiert in den nachf...","Bono, Nr. 70).",Terminus ante für die nachfolgenden Briefe Nr....,Der Hinweis auf die künftige Erhebung zum Kard...,NaN,NaN,...,reuocare unanimiter disposuit (Gregor von Sabi...,"monito (Oktavian, Nr. 65) - quem dominus papa...",Nr. 68) - a domino papa et tota curia ad hoc ...,Wir stellen im folgenden die Briefe des Petrus...,NaN,NaN,229-230,226-227,[230 ],[Nr. 28-29 zyxwvutsrqponmlkjihgfedcbaZYXWVUTSR...
20,58.,(1159 vor September 1).,NaN,Kardinaldiakon P(etrus) von S. Eustachius emp...,Kopie s. XVII aus verlorener Briefsammlung vo...,Die Emendation O. > A. für den Empfänger (Anm...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,230-231,227-228,[Nr. 32-33 ],[231 zyxwvutsrqponmlkjihgfedcbaZYXWVU]
21,59.,(1159 vor September 1).,NaN,Kardinaldiakon (Petrus) von S. Eustachius eri...,Kopie s. XVII aus verlorener Briefsammlung vo...,Der Bezug auf Alexius ergibt sich durch seine ...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,231-232,228-229,[232 ],[Nr. 28-29 zyxwvutsrqponmlkjihgfedcbaZYXWVUTSR...
22,60.,(1159 vor September 1).,NaN,Kardinaldiakon (Petrus) von S. Eustachius bit...,Kopie s. XVII aus verlorener Briefsammlung vo...,') Abt Odo II. von St-Denis 1151-62.,NaN,NaN,NaN,NaN,...,2) Siehe auch Nr. 61. xvutsrqponmlihgfedcbaXVU...,NaN,NaN,NaN,NaN,NaN,232-233,229-230,[Nr. 32-33 ],[233 ]
23,61.,NaN,NaN,Gleichlautender Bittbrief desselben Kardinals ...,Datum und Überlieferung wie Nr. 60. Der Gruß a...,'`> adempto G `. b`> folgt A gestrichen G4.,') Abt Ansold von St-Corneille in Compiègne ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,233,230,[],[]
24,62.,(1159 vor September 1).,NaN,Nach einstimmigem Beschluß des Papstes (Hadria...,Kopien s. XVII aus verlorener Briefsammlung v...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,233,230,[],[]

## EXPORT AS CSV

In [45]:
# show path and page range of the input to manually adjust the name of the output file
print(f"{filename}   {parameter['pdf_pages']} First page: {parameter['first_print_page']}")

PUU_in_Frankreich_NF_8_Paris_I_Markiert.pdf   (205, 230) First page: 208

In [46]:
exportname = parameter['path'].replace('.pdf', '')
exportpath = f"{exportname}_{parameter['pdf_pages'][0]}-{parameter['pdf_pages'][1]}.csv"
export_df_reorderd.to_csv(exportpath, index=True)
print(exportpath)

PUU_in_Frankreich_NF_8_Paris_I_Markiert_205-230.csv